AZURE_API_KEY = "6Fuap4w3yZTjqVevfICj1M8YXkYN4FIn2hEljeAwmfBvSp6R1jOYJQQJ99BCACYeBjFXJ3w3AAABACOG6efF"
AZURE_ENDPOINT = "https://hand-tracking-writing.openai.azure.com/"
AZURE_API_VERSION = "2023-12-01-preview"
AZURE_DEPLOYMENT_NAME = "dall-e-3"